# Generated by Django 4.2.6 on 2023-10-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
    ]
