# Generated by Django 4.2.6 on 2023-10-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='maths', max_length=100),
            preserve_default=False,
        ),
    ]
